<?php
date_default_timezone_set('Asia/Jakarta');
include "function.php";
<pre id="tiresult" style="font-size: 13px; background-color: #ffffff; font-weight: bold; padding: 4px 5px; --fs: 13px;"><b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondr</b>
<b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGo</b>
<b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondron</b>
<b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGond</b>
<b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongG</b>
<b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondro</b>
<b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGon</b>
<b style="color:#FFFFFF">drongGondrongGondrongGondrongGondrongGondrongGondrongGond</b><b style="color:#FDFDFD">r</b><b style="color:#F7F6F7">o</b><b style="color:#F0F0F0">n</b><b style="color:#E4E5E6">g</b><b style="color:#DCDDE1">G</b><b style="color:#DADCDF">o</b><b style="color:#DCDDE1">n</b><b style="color:#E3E3E4">d</b><b style="color:#EEEDED">r</b><b style="color:#F4F3F3">o</b><b style="color:#F9F9F9">n</b><b style="color:#FEFEFE">g</b><b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondrongGondrong</b>
<b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondrongGondr</b><b style="color:#E9E9EA">o</b><b style="color:#9C9B9B">n</b><b style="color:#3E3E3E">g</b><b style="color:#131313">G</b><b style="color:#080707">o</b><b style="color:#010101">n</b><b style="color:#000000">d</b><b style="color:#020200">r</b><b style="color:#0C0700">o</b><b style="color:#0B0600">n</b><b style="color:#0C0800">g</b><b style="color:#020100">G</b><b style="color:#000000">o</b><b style="color:#010101">n</b><b style="color:#060606">d</b><b style="color:#0B0B0B">r</b><b style="color:#202020">o</b><b style="color:#5E5E5E">n</b><b style="color:#B8B8B8">g</b><b style="color:#F6F6F6">G</b><b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongGondrongGondr</b>
<b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGondrongGondrong</b><b style="color:#B0B0B0">G</b><b style="color:#16181B">o</b><b style="color:#000000">nd</b><b style="color:#252525">r</b><b style="color:#AAAAAB">o</b><b style="color:#D8D8DE">n</b><b style="color:#5B5D60">g</b><b style="color:#000000">G</b><b style="color:#160E01">o</b><b style="color:#FCD701">n</b><b style="color:#FFE100">d</b><b style="color:#FCD701">r</b><b style="color:#160E01">o</b><b style="color:#000000">n</b><b style="color:#616364">g</b><b style="color:#E8E8EA">G</b><b style="color:#CFCFD2">o</b><b style="color:#515154">n</b><b style="color:#000000">dr</b><b style="color:#000102">o</b><b style="color:#414142">n</b><b style="color:#E9E9E9">g</b><b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondrongGo</b>
<b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongGondrongGon</b><b style="color:#F3F2F3">d</b><b style="color:#202021">r</b><b style="color:#000000">o</b><b style="color:#300E02">n</b><b style="color:#692708">g</b><b style="color:#000000">G</b><b style="color:#060808">o</b><b style="color:#BFC2C5">n</b><b style="color:#FFFFFF">d</b><b style="color:#D0D2D7">r</b><b style="color:#000000">o</b><b style="color:#030200">n</b><b style="color:#FAD401">g</b><b style="color:#FFEC00">G</b><b style="color:#FBD601">o</b><b style="color:#040200">n</b><b style="color:#000000">d</b><b style="color:#D6D6DA">r</b><b style="color:#FFFFFF">o</b><b style="color:#BABDC2">n</b><b style="color:#050709">g</b><b style="color:#000000">G</b><b style="color:#82300A">o</b><b style="color:#9E3D0C">n</b><b style="color:#020000">d</b><b style="color:#000000">r</b><b style="color:#A7A7A7">o</b><b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondrongGondron</b>
<b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondrongGondron</b><b style="color:#F5F5F5">g</b><b style="color:#0A0A0A">G</b><b style="color:#000000">o</b><b style="color:#110602">n</b><b style="color:#FB8B1F">d</b><b style="color:#FFAB23">r</b><b style="color:#DF6718">o</b><b style="color:#0F0401">n</b><b style="color:#000000">g</b><b style="color:#57585B">G</b><b style="color:#E7E7EB">o</b><b style="color:#0A0B0B">n</b><b style="color:#000000">d</b><b style="color:#BB8A02">r</b><b style="color:#FFF100">o</b><b style="color:#BB8B01">n</b><b style="color:#000000">g</b><b style="color:#0B0C0C">G</b><b style="color:#E7E7EB">o</b><b style="color:#55555A">n</b><b style="color:#000000">d</b><b style="color:#100401">r</b><b style="color:#E16917">o</b><b style="color:#FFA822">n</b><b style="color:#FF961D">g</b><b style="color:#331104">G</b><b style="color:#000000">on</b><b style="color:#CAC9CA">d</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondrongGond</b>
<b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondrongGond</b><b style="color:#444444">r</b><b style="color:#000000">ong</b><b style="color:#0D0401">G</b><b style="color:#5D2005">o</b><b style="color:#B84B0E">n</b><b style="color:#C14F0F">d</b><b style="color:#250B03">r</b><b style="color:#000000">o</b><b style="color:#0E0E0E">n</b><b style="color:#171717">g</b><b style="color:#000000">G</b><b style="color:#140E01">o</b><b style="color:#F7D104">n</b><b style="color:#150D01">d</b><b style="color:#000000">r</b><b style="color:#171817">o</b><b style="color:#0D0E0E">n</b><b style="color:#000000">g</b><b style="color:#230C02">G</b><b style="color:#C15210">o</b><b style="color:#BA480C">n</b><b style="color:#5B2105">d</b><b style="color:#0C0401">r</b><b style="color:#000000">ong</b><b style="color:#1A1A1A">G</b><b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongGondrongG</b>
<b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongGondrong</b><b style="color:#F3F3F3">G</b><b style="color:#010101">o</b><b style="color:#000000">n</b><b style="color:#181414">d</b><b style="color:#000000">ro</b><b style="color:#000211">n</b><b style="color:#000319">g</b><b style="color:#00020A">G</b><b style="color:#020205">o</b><b style="color:#000001">n</b><b style="color:#000000">dron</b><b style="color:#1C1702">g</b><b style="color:#000000">Gondr</b><b style="color:#020204">o</b><b style="color:#000209">n</b><b style="color:#000318">g</b><b style="color:#000212">G</b><b style="color:#000000">on</b><b style="color:#1F1919">d</b><b style="color:#010101">r</b><b style="color:#000000">o</b><b style="color:#EBEBEB">n</b><b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondrongGondro</b>
<b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondrongGondr</b><b style="color:#D5D5D5">o</b><b style="color:#000000">n</b><b style="color:#050404">g</b><b style="color:#F3D2D9">G</b><b style="color:#72575A">o</b><b style="color:#010100">n</b><b style="color:#000002">d</b><b style="color:#000931">r</b><b style="color:#001461">o</b><b style="color:#001158">n</b><b style="color:#000725">g</b><b style="color:#000000">Go</b><b style="color:#030202">n</b><b style="color:#000000">dro</b><b style="color:#030202">n</b><b style="color:#000000">gG</b><b style="color:#000725">o</b><b style="color:#00135D">n</b><b style="color:#001560">d</b><b style="color:#000933">r</b><b style="color:#000002">o</b><b style="color:#010101">n</b><b style="color:#74575B">g</b><b style="color:#F5D8DF">G</b><b style="color:#070506">o</b><b style="color:#000000">n</b><b style="color:#D0CFD0">d</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondrongGon</b>
<b style="color:#FFFFFF">drongGondrongGondrongGondrongGondrongGondrongGo</b><b style="color:#DFDFDF">n</b><b style="color:#000000">d</b><b style="color:#010101">r</b><b style="color:#F7D5DD">o</b><b style="color:#FFEFF5">n</b><b style="color:#EBC7CF">g</b><b style="color:#876669">G</b><b style="color:#392625">o</b><b style="color:#1D1212">n</b><b style="color:#181110">d</b><b style="color:#2B1D1F">r</b><b style="color:#553E41">o</b><b style="color:#A8858B">n</b><b style="color:#8A6972">g</b><b style="color:#000000">Gon</b><b style="color:#906D75">d</b><b style="color:#A8838A">r</b><b style="color:#573E41">o</b><b style="color:#2D1D1F">n</b><b style="color:#171011">g</b><b style="color:#1C1211">G</b><b style="color:#392623">o</b><b style="color:#886769">n</b><b style="color:#EEC7D0">d</b><b style="color:#FFEEF6">r</b><b style="color:#F8D7E0">o</b><b style="color:#010101">n</b><b style="color:#000000">g</b><b style="color:#DCDADC">G</b><b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongGondrong</b>
<b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondron</b><b style="color:#D8DAD5">g</b><b style="color:#29390D">G</b><b style="color:#7C694F">o</b><b style="color:#FEE6EE">n</b><b style="color:#FFEBF2">d</b><b style="color:#FFEEF3">r</b><b style="color:#FFF1F6">o</b><b style="color:#FFEFF5">n</b><b style="color:#FFEEF4">g</b><b style="color:#FFECF1">G</b><b style="color:#D5ADB6">o</b><b style="color:#48353C">n</b><b style="color:#0E090C">d</b><b style="color:#040402">r</b><b style="color:#000000">ong</b><b style="color:#040402">G</b><b style="color:#0E0A0D">o</b><b style="color:#4B353C">n</b><b style="color:#D6ABB4">d</b><b style="color:#FFEBF0">r</b><b style="color:#FFEEF3">o</b><b style="color:#FFEFF5">n</b><b style="color:#FFEFF6">g</b><b style="color:#FFECF3">G</b><b style="color:#FFEAF2">o</b><b style="color:#FEE7EE">n</b><b style="color:#856C60">d</b><b style="color:#2D3813">r</b><b style="color:#D9DCD4">o</b><b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondrongGondr</b>
<b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGondrongGon</b><b style="color:#F4F3F4">d</b><b style="color:#0A0A0A">r</b><b style="color:#000100">o</b><b style="color:#614C45">n</b><b style="color:#E2B8C6">g</b><b style="color:#FADCE4">G</b><b style="color:#FDE2EA">o</b><b style="color:#FDE3EA">n</b><b style="color:#FBDDE5">d</b><b style="color:#DCB1BA">r</b><b style="color:#38262B">o</b><b style="color:#000000">n</b><b style="color:#020700">g</b><b style="color:#336000">G</b><b style="color:#3D7500">o</b><b style="color:#316101">n</b><b style="color:#284805">d</b><b style="color:#3C6A02">r</b><b style="color:#417A00">o</b><b style="color:#316300">n</b><b style="color:#020700">g</b><b style="color:#000000">G</b><b style="color:#38252B">o</b><b style="color:#DDB0BD">n</b><b style="color:#FBDDE6">d</b><b style="color:#FDE2EB">r</b><b style="color:#FDE3EB">o</b><b style="color:#FADCE4">n</b><b style="color:#E6BDC7">g</b><b style="color:#6D5555">G</b><b style="color:#010100">o</b><b style="color:#090A09">n</b><b style="color:#F2F1F2">d</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondrongGo</b>
<b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongGon</b><b style="color:#F7FDE1">d</b><b style="color:#ECF9B6">r</b><b style="color:#ECF9BA">o</b><b style="color:#F8FDE4">n</b><b style="color:#FFFFFF">gG</b><b style="color:#EEF1E7">o</b><b style="color:#495835">n</b><b style="color:#020600">d</b><b style="color:#010200">r</b><b style="color:#070605">o</b><b style="color:#100D0A">n</b><b style="color:#0F0C0B">g</b><b style="color:#070606">G</b><b style="color:#000100">o</b><b style="color:#060C01">n</b><b style="color:#7A8D5B">d</b><b style="color:#E1F3A8">r</b><b style="color:#A4C35E">o</b><b style="color:#000000">n</b><b style="color:#020300">g</b><b style="color:#1F2D09">G</b><b style="color:#040800">o</b><b style="color:#000000">n</b><b style="color:#87A549">d</b><b style="color:#E1F3A8">r</b><b style="color:#7D905B">o</b><b style="color:#060C01">n</b><b style="color:#000100">g</b><b style="color:#080606">G</b><b style="color:#100C0C">o</b><b style="color:#110D0B">n</b><b style="color:#080605">d</b><b style="color:#010200">r</b><b style="color:#040901">o</b><b style="color:#3E4F2D">n</b><b style="color:#EBF0E7">g</b><b style="color:#FFFFFF">Go</b><b style="color:#F7FDE1">n</b><b style="color:#ECF9B8">d</b><b style="color:#EBF9BA">r</b><b style="color:#F7FDE3">o</b><b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondron</b>
<b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondro</b><b style="color:#FDFEF5">n</b><b style="color:#B1E72D">g</b><b style="color:#80D500">G</b><b style="color:#80D100">on</b><b style="color:#87D400">d</b><b style="color:#BAE83C">r</b><b style="color:#FEFFFB">o</b><b style="color:#EBF9BA">n</b><b style="color:#8DDF03">g</b><b style="color:#7CD101">G</b><b style="color:#67B601">o</b><b style="color:#448001">n</b><b style="color:#0E2500">d</b><b style="color:#1C4000">r</b><b style="color:#55A100">o</b><b style="color:#67BA00">n</b><b style="color:#87D502">g</b><b style="color:#99E006">G</b><b style="color:#96DF06">o</b><b style="color:#5E950A">n</b><b style="color:#000000">dr</b><b style="color:#000202">o</b><b style="color:#000000">ng</b><b style="color:#5E9509">G</b><b style="color:#93E105">o</b><b style="color:#95E106">n</b><b style="color:#7FD201">d</b><b style="color:#66B800">r</b><b style="color:#549F00">o</b><b style="color:#193D00">n</b><b style="color:#0C2100">g</b><b style="color:#478201">G</b><b style="color:#6CB602">o</b><b style="color:#80D202">n</b><b style="color:#90DE04">d</b><b style="color:#EFFBC5">r</b><b style="color:#FEFFFA">o</b><b style="color:#B3E833">n</b><b style="color:#85D700">g</b><b style="color:#7FD400">G</b><b style="color:#7CD400">o</b><b style="color:#83D600">n</b><b style="color:#B7E831">d</b><b style="color:#FDFFF7">r</b><b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGond</b>
<b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGon</b><b style="color:#E3F79E">d</b><b style="color:#75D100">r</b><b style="color:#85D600">o</b><b style="color:#87D500">ng</b><b style="color:#85D400">G</b><b style="color:#80D000">o</b><b style="color:#F1FAC1">n</b><b style="color:#E8F7B3">d</b><b style="color:#7CD600">r</b><b style="color:#87D700">o</b><b style="color:#8EDD00">n</b><b style="color:#6FB603">g</b><b style="color:#060B02">G</b><b style="color:#000000">o</b><b style="color:#182F01">n</b><b style="color:#72BE03">d</b><b style="color:#8BDF00">r</b><b style="color:#88D800">o</b><b style="color:#8DDC00">n</b><b style="color:#427402">g</b><b style="color:#000000">G</b><b style="color:#000101">o</b><b style="color:#021B14">n</b><b style="color:#000100">d</b><b style="color:#000000">r</b><b style="color:#417503">o</b><b style="color:#8ADD00">n</b><b style="color:#87D800">g</b><b style="color:#8DE000">G</b><b style="color:#78C505">o</b><b style="color:#1C3402">n</b><b style="color:#000000">d</b><b style="color:#060B02">r</b><b style="color:#77BA02">o</b><b style="color:#8DDD00">n</b><b style="color:#87D700">g</b><b style="color:#7FD400">G</b><b style="color:#ECF9BB">o</b><b style="color:#EFFAC3">n</b><b style="color:#78D100">d</b><b style="color:#82D700">r</b><b style="color:#87D500">on</b><b style="color:#85D500">g</b><b style="color:#7FD200">G</b><b style="color:#E6F9B1">o</b><b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongG</b>
<b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrong</b><b style="color:#E0F799">G</b><b style="color:#7AD100">o</b><b style="color:#83D800">n</b><b style="color:#87D500">d</b><b style="color:#87D400">ro</b><b style="color:#83D200">n</b><b style="color:#EFFBBB">g</b><b style="color:#E8F8B6">G</b><b style="color:#7FD500">o</b><b style="color:#87D600">n</b><b style="color:#87D500">d</b><b style="color:#8AD900">r</b><b style="color:#82CB01">o</b><b style="color:#2F4E04">n</b><b style="color:#000000">g</b><b style="color:#000100">G</b><b style="color:#2E4F02">o</b><b style="color:#7AC201">n</b><b style="color:#92E600">d</b><b style="color:#477D03">r</b><b style="color:#000000">o</b><b style="color:#000100">n</b><b style="color:#021B13">g</b><b style="color:#000100">G</b><b style="color:#000000">o</b><b style="color:#457804">n</b><b style="color:#95E500">d</b><b style="color:#80C701">r</b><b style="color:#365E02">o</b><b style="color:#010200">n</b><b style="color:#000000">g</b><b style="color:#234202">G</b><b style="color:#80C901">o</b><b style="color:#8BD900">n</b><b style="color:#87D500">dr</b><b style="color:#80D400">o</b><b style="color:#EDF9BD">n</b><b style="color:#EEFAC3">g</b><b style="color:#77D400">G</b><b style="color:#85D600">o</b><b style="color:#87D400">nd</b><b style="color:#87D600">r</b><b style="color:#82D400">o</b><b style="color:#E5F8AD">n</b><b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondro</b>
<b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondr</b><b style="color:#DFF799">o</b><b style="color:#77D200">n</b><b style="color:#85D900">g</b><b style="color:#87D700">G</b><b style="color:#87D400">on</b><b style="color:#83D200">d</b><b style="color:#EEFBBB">r</b><b style="color:#E7F8B6">o</b><b style="color:#7FD500">n</b><b style="color:#87D500">g</b><b style="color:#87D400">G</b><b style="color:#87D500">o</b><b style="color:#88D700">n</b><b style="color:#90DD00">d</b><b style="color:#77BA02">r</b><b style="color:#213903">o</b><b style="color:#000000">n</b><b style="color:#010200">g</b><b style="color:#2A4C02">G</b><b style="color:#5A9008">o</b><b style="color:#010201">n</b><b style="color:#000000">d</b><b style="color:#010A07">r</b><b style="color:#000000">o</b><b style="color:#010100">n</b><b style="color:#5A8D08">g</b><b style="color:#2E5501">G</b><b style="color:#020300">o</b><b style="color:#000001">n</b><b style="color:#162A01">d</b><b style="color:#69AD01">r</b><b style="color:#90DD00">o</b><b style="color:#8AD800">n</b><b style="color:#87D400">g</b><b style="color:#87D500">Go</b><b style="color:#80D400">n</b><b style="color:#EDF9BD">d</b><b style="color:#EEFAC6">r</b><b style="color:#75D400">o</b><b style="color:#87D500">n</b><b style="color:#87D400">g</b><b style="color:#87D500">G</b><b style="color:#87D600">o</b><b style="color:#82D400">n</b><b style="color:#E6F9AD">d</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGon</b>
<b style="color:#FFFFFF">drongGondrongGondrongGondrongGondrongGo</b><b style="color:#DFF799">n</b><b style="color:#77D200">d</b><b style="color:#85D900">r</b><b style="color:#87D700">o</b><b style="color:#87D400">ng</b><b style="color:#83D200">G</b><b style="color:#EFFBBB">o</b><b style="color:#E8F8B6">n</b><b style="color:#7DD600">d</b><b style="color:#87D600">r</b><b style="color:#87D400">o</b><b style="color:#87D500">ngG</b><b style="color:#8AD900">o</b><b style="color:#90DC00">n</b><b style="color:#71B601">d</b><b style="color:#284703">r</b><b style="color:#020300">o</b><b style="color:#000001">n</b><b style="color:#000000">gGond</b><b style="color:#000001">r</b><b style="color:#010201">o</b><b style="color:#223C02">n</b><b style="color:#6AB301">g</b><b style="color:#8DDA00">G</b><b style="color:#8BD900">o</b><b style="color:#87D600">n</b><b style="color:#87D500">dron</b><b style="color:#80D400">g</b><b style="color:#EDF9BD">G</b><b style="color:#EEFAC3">o</b><b style="color:#75D400">n</b><b style="color:#87D500">dro</b><b style="color:#87D600">n</b><b style="color:#82D400">g</b><b style="color:#E6F9AD">G</b><b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrong</b>
<b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondron</b><b style="color:#E0F799">g</b><b style="color:#77D200">G</b><b style="color:#85D900">o</b><b style="color:#87D700">n</b><b style="color:#87D400">dr</b><b style="color:#83D200">o</b><b style="color:#EEFBBB">n</b><b style="color:#E7F8B6">g</b><b style="color:#80D400">G</b><b style="color:#87D500">ondro</b><b style="color:#87D400">n</b><b style="color:#87D500">g</b><b style="color:#8AD800">G</b><b style="color:#90DF00">o</b><b style="color:#7FC901">n</b><b style="color:#427202">d</b><b style="color:#0E1701">r</b><b style="color:#000000">ong</b><b style="color:#0E1B01">G</b><b style="color:#427202">o</b><b style="color:#80C601">n</b><b style="color:#90DD00">d</b><b style="color:#8ADC00">r</b><b style="color:#87D800">o</b><b style="color:#87D500">ngGond</b><b style="color:#80D400">r</b><b style="color:#EDF9BD">o</b><b style="color:#EEFAC3">n</b><b style="color:#75D400">g</b><b style="color:#87D500">Gon</b><b style="color:#87D600">d</b><b style="color:#82D400">r</b><b style="color:#E6F9AD">o</b><b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondr</b>
<b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGond</b><b style="color:#DFF799">r</b><b style="color:#77D200">o</b><b style="color:#85D900">n</b><b style="color:#87D700">g</b><b style="color:#87D400">Go</b><b style="color:#83D200">n</b><b style="color:#EFFBBB">d</b><b style="color:#E8F8B6">r</b><b style="color:#7DD600">o</b><b style="color:#87D600">n</b><b style="color:#87D400">g</b><b style="color:#87D500">Gondron</b><b style="color:#88D800">g</b><b style="color:#8EDD00">G</b><b style="color:#90D901">o</b><b style="color:#396003">n</b><b style="color:#040900">d</b><b style="color:#365D03">r</b><b style="color:#8EDE01">o</b><b style="color:#8EDE00">n</b><b style="color:#88D800">g</b><b style="color:#87D500">Gon</b><b style="color:#87D400">d</b><b style="color:#87D500">rongG</b><b style="color:#80D400">o</b><b style="color:#EDF9BD">n</b><b style="color:#EEFAC3">d</b><b style="color:#74D500">r</b><b style="color:#85D600">o</b><b style="color:#87D400">n</b><b style="color:#87D500">g</b><b style="color:#87D600">G</b><b style="color:#82D400">o</b><b style="color:#E6F9AD">n</b><b style="color:#FFFFFF">drongGondrongGondrongGondrongGondrongGo</b>
<b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongG</b><b style="color:#DFF795">o</b><b style="color:#75D200">n</b><b style="color:#85D900">d</b><b style="color:#87D700">r</b><b style="color:#87D400">on</b><b style="color:#82D100">g</b><b style="color:#EEFBBA">G</b><b style="color:#E8F8B6">o</b><b style="color:#80D500">n</b><b style="color:#87D500">drongGond</b><b style="color:#87D400">ro</b><b style="color:#88D500">n</b><b style="color:#8BDA00">g</b><b style="color:#87D500">G</b><b style="color:#8BDA00">o</b><b style="color:#88D600">n</b><b style="color:#87D500">d</b><b style="color:#87D400">r</b><b style="color:#87D500">ongGondro</b><b style="color:#80D400">n</b><b style="color:#EDF9BD">g</b><b style="color:#ECFAC1">G</b><b style="color:#75D400">o</b><b style="color:#87D500">n</b><b style="color:#87D400">d</b><b style="color:#87D500">r</b><b style="color:#87D600">o</b><b style="color:#80D400">n</b><b style="color:#E4F8AA">g</b><b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondron</b>
<b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondro</b><b style="color:#ECFAC1">n</b><b style="color:#7FD400">g</b><b style="color:#80D400">G</b><b style="color:#83D400">on</b><b style="color:#7FD400">d</b><b style="color:#88D400">r</b><b style="color:#F7FCD9">o</b><b style="color:#E8F7B1">n</b><b style="color:#7DD700">g</b><b style="color:#87D600">G</b><b style="color:#87D400">o</b><b style="color:#87D500">ndrongGondr</b><b style="color:#88D600">o</b><b style="color:#87D500">n</b><b style="color:#87D400">g</b><b style="color:#87D500">GondrongGon</b><b style="color:#80D400">d</b><b style="color:#ECF9BB">r</b><b style="color:#F4FCD9">o</b><b style="color:#7DD400">n</b><b style="color:#7FD200">g</b><b style="color:#83D200">Go</b><b style="color:#7FD400">n</b><b style="color:#83D600">d</b><b style="color:#F1FBD0">r</b><b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGond</b>
<b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGond</b><b style="color:#EAF8B6">r</b><b style="color:#B4E62A">o</b><b style="color:#9EE00D">n</b><b style="color:#9EDF0D">g</b><b style="color:#B4E82F">G</b><b style="color:#ECFABD">o</b><b style="color:#FFFFFF">n</b><b style="color:#E5F6AB">d</b><b style="color:#80D600">r</b><b style="color:#87D600">o</b><b style="color:#87D400">n</b><b style="color:#87D500">gGondrongGondrongGondrong</b><b style="color:#80D400">G</b><b style="color:#E9F8B4">o</b><b style="color:#FFFFFF">n</b><b style="color:#ECF9B7">d</b><b style="color:#B6E62D">r</b><b style="color:#A1DF0F">o</b><b style="color:#9FDF0F">n</b><b style="color:#B3E629">g</b><b style="color:#E9F9B7">G</b><b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongG</b>
<b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongGon</b><b style="color:#FFFFFD">d</b><b style="color:#FFFFFE">r</b><b style="color:#FFFFFF">ong</b><b style="color:#E4F6A8">G</b><b style="color:#7FD400">o</b><b style="color:#87D500">n</b><b style="color:#87D400">drong</b><b style="color:#87D500">Gond</b><b style="color:#87D400">rongGon</b><b style="color:#87D500">drong</b><b style="color:#87D400">Gond</b><b style="color:#87D500">r</b><b style="color:#7DD200">o</b><b style="color:#E8F8B4">n</b><b style="color:#FFFFFF">gGo</b><b style="color:#FFFFFE">nd</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondro</b>
<b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondrongGondr</b><b style="color:#FAFEEB">o</b><b style="color:#A2E016">n</b><b style="color:#80D100">g</b><b style="color:#7FD200">Gon</b><b style="color:#83D400">d</b><b style="color:#87D600">r</b><b style="color:#87D500">ongGo</b><b style="color:#7FD500">n</b><b style="color:#7CD200">d</b><b style="color:#7FD200">ro</b><b style="color:#82D400">n</b><b style="color:#87D700">g</b><b style="color:#87D500">Gondr</b><b style="color:#80D500">o</b><b style="color:#7CD200">n</b><b style="color:#7FD200">gG</b><b style="color:#80D100">o</b><b style="color:#A5E217">n</b><b style="color:#FBFEF1">d</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondrongGon</b>
<b style="color:#FFFFFF">drongGondrongGondrongGondrongGondrongGondrongGon</b><b style="color:#FEFFFC">d</b><b style="color:#EDF9BE">r</b><b style="color:#D8F380">o</b><b style="color:#D7F375">n</b><b style="color:#D9F37C">g</b><b style="color:#B3E82F">G</b><b style="color:#80D700">o</b><b style="color:#87D500">n</b><b style="color:#87D400">dr</b><b style="color:#87D500">o</b><b style="color:#87D700">n</b><b style="color:#BFED42">g</b><b style="color:#D8F47D">G</b><b style="color:#D7F375">o</b><b style="color:#D9F47D">n</b><b style="color:#BDEB39">d</b><b style="color:#83D700">r</b><b style="color:#87D500">o</b><b style="color:#87D400">n</b><b style="color:#87D500">gG</b><b style="color:#83D500">o</b><b style="color:#B4E82B">n</b><b style="color:#D6F47A">d</b><b style="color:#D6F377">r</b><b style="color:#D9F382">o</b><b style="color:#EEFAC6">n</b><b style="color:#FEFFFC">g</b><b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondrong</b>
<b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondrongGondr</b><b style="color:#E2F8A5">o</b><b style="color:#7DD400">n</b><b style="color:#87D700">g</b><b style="color:#87D500">Go</b><b style="color:#87D400">n</b><b style="color:#88D501">d</b><b style="color:#F4FCD6">r</b><b style="color:#FFFFFF">ong</b><b style="color:#F0FBC6">G</b><b style="color:#82D200">o</b><b style="color:#87D500">ndro</b><b style="color:#82D100">n</b><b style="color:#E7F698">g</b><b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondrongGondrongGondr</b>
<b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGondrongGondrongGo</b><b style="color:#E0F79E">n</b><b style="color:#7CD400">d</b><b style="color:#87D600">r</b><b style="color:#87D500">on</b><b style="color:#87D400">g</b><b style="color:#88D500">G</b><b style="color:#F2FBD0">o</b><b style="color:#FFFFFF">ndr</b><b style="color:#EEFBBF">o</b><b style="color:#83D200">n</b><b style="color:#87D400">g</b><b style="color:#87D500">Gon</b><b style="color:#83D100">d</b><b style="color:#E6F692">r</b><b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGondrongGondrongGo</b>
<b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongGondrongGondron</b><b style="color:#E0F796">g</b><b style="color:#7DD400">G</b><b style="color:#85D800">o</b><b style="color:#87D500">n</b><b style="color:#87D400">dro</b><b style="color:#F1FBCC">n</b><b style="color:#FFFFFF">gGo</b><b style="color:#EEFABD">n</b><b style="color:#82D100">d</b><b style="color:#87D500">rong</b><b style="color:#82D100">G</b><b style="color:#E4F690">o</b><b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongGondrongGondron</b>
<b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondrongGondrongGond</b><b style="color:#ECF9B7">r</b><b style="color:#7AD400">o</b><b style="color:#7CD500">n</b><b style="color:#83D400">g</b><b style="color:#83D200">G</b><b style="color:#7FD100">o</b><b style="color:#8ED603">n</b><b style="color:#F7FDE4">d</b><b style="color:#FFFFFF">ron</b><b style="color:#F7FCDD">g</b><b style="color:#8AD501">G</b><b style="color:#7FD400">o</b><b style="color:#82D600">n</b><b style="color:#83D200">d</b><b style="color:#80D200">r</b><b style="color:#82D200">o</b><b style="color:#EEF9BD">n</b><b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondrongGondrongGond</b>
<b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondrongGondrongGo</b><b style="color:#E8F9B4">n</b><b style="color:#B4E72B">d</b><b style="color:#A4E013">r</b><b style="color:#A4E112">o</b><b style="color:#BBE938">n</b><b style="color:#F2FBD1">g</b><b style="color:#FFFFFF">Gondr</b><b style="color:#F0FACA">o</b><b style="color:#BAE836">n</b><b style="color:#A4E211">g</b><b style="color:#A4E111">G</b><b style="color:#B4E82B">o</b><b style="color:#E9F9B8">n</b><b style="color:#FFFFFF">drongGondrongGondrongGondrongGondrongGondrongGondrongG</b>
<b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongG</b><b style="color:#FFFFFD">o</b><b style="color:#FFFFFF">ndr</b><b style="color:#FFFFF9">o</b><b style="color:#FFFFFF">ngGondr</b><b style="color:#FFFFFE">o</b><b style="color:#FFFFFF">ngGo</b><b style="color:#FFFFFE">n</b><b style="color:#FFFFFF">d</b><b style="color:#FFFFFC">r</b><b style="color:#FFFFF5">o</b><b style="color:#FFFFF3">n</b><b style="color:#FFFFFE">g</b><b style="color:#FFFFFF">Gond</b><b style="color:#FFFFFE">ro</b><b style="color:#FFFFFF">ngGondrongGondro</b><b style="color:#FFFFFE">n</b><b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondro</b>
<b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondr</b><b style="color:#FFFFF6">o</b><b style="color:#F2FF31">n</b><b style="color:#FFFFFC">g</b><b style="color:#FFFFFF">G</b><b style="color:#FBFFAA">o</b><b style="color:#F1FF2A">n</b><b style="color:#FAFF99">d</b><b style="color:#FFFFFF">ron</b><b style="color:#FFFFFE">g</b><b style="color:#F7FF74">G</b><b style="color:#FFFFFE">o</b><b style="color:#FDFFCC">n</b><b style="color:#FDFFD6">d</b><b style="color:#FFFFFF">rong</b><b style="color:#FFFFFB">G</b><b style="color:#F8FF7A">o</b><b style="color:#F6FF60">n</b><b style="color:#F7FF6D">d</b><b style="color:#FCFFBB">r</b><b style="color:#FFFFFF">ongG</b><b style="color:#FEFFD8">o</b><b style="color:#FFFFF2">n</b><b style="color:#FFFFFF">drongGond</b><b style="color:#FEFFD6">r</b><b style="color:#FBFF9F">o</b><b style="color:#FFFFFF">ngGo</b><b style="color:#FFFFF9">n</b><b style="color:#F7FF64">d</b><b style="color:#F9FF95">r</b><b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGon</b>
<b style="color:#FFFFFF">drongGondrongGondrongGondrongGondrongGo</b><b style="color:#FDFFD5">n</b><b style="color:#ECFF0D">d</b><b style="color:#FFFFF3">r</b><b style="color:#FFFFFB">o</b><b style="color:#F6FF57">n</b><b style="color:#FCFFBE">g</b><b style="color:#F5FF63">G</b><b style="color:#FFFFF7">o</b><b style="color:#FEFFEA">n</b><b style="color:#FFFFF6">d</b><b style="color:#FFFFF1">r</b><b style="color:#FBFFA1">o</b><b style="color:#FFFFFF">n</b><b style="color:#FEFFE8">gG</b><b style="color:#FEFFEC">o</b><b style="color:#FDFFC3">n</b><b style="color:#FFFFF9">d</b><b style="color:#FFFFFF">r</b><b style="color:#FFFFF9">o</b><b style="color:#FDFFD7">n</b><b style="color:#FDFFBF">g</b><b style="color:#FEFFDA">G</b><b style="color:#FBFFA1">o</b><b style="color:#FEFFED">n</b><b style="color:#FFFFFD">d</b><b style="color:#FEFFE8">r</b><b style="color:#FFFFFC">o</b><b style="color:#F5FF52">n</b><b style="color:#F9FF7C">g</b><b style="color:#FFFFF6">G</b><b style="color:#FFFFFF">o</b><b style="color:#FEFFE7">n</b><b style="color:#FEFFED">d</b><b style="color:#FFFFFF">r</b><b style="color:#FEFFEC">o</b><b style="color:#FFFFF9">n</b><b style="color:#FEFFE4">g</b><b style="color:#FFFFFC">G</b><b style="color:#FDFFC6">o</b><b style="color:#FDFFD0">n</b><b style="color:#FFFFFF">dr</b><b style="color:#FDFFCC">o</b><b style="color:#FEFFE6">n</b><b style="color:#FFFFFF">g</b><b style="color:#FFFFFC">G</b><b style="color:#F9FF93">o</b><b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrong</b>
<b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGondron</b><b style="color:#FDFFBE">g</b><b style="color:#F7FF72">G</b><b style="color:#FDFFDE">o</b><b style="color:#FEFFE8">n</b><b style="color:#F2FF2B">d</b><b style="color:#FEFFEC">r</b><b style="color:#FEFFDA">o</b><b style="color:#F0FF20">n</b><b style="color:#F3FF30">g</b><b style="color:#F4FF49">G</b><b style="color:#FBFFAA">o</b><b style="color:#F7FF66">n</b><b style="color:#FFFFF5">d</b><b style="color:#FFFFFF">r</b><b style="color:#FFFFF9">o</b><b style="color:#F5FF58">n</b><b style="color:#F8FF75">g</b><b style="color:#FAFF9F">G</b><b style="color:#FFFFFF">ond</b><b style="color:#FCFFAD">r</b><b style="color:#FFFFF3">o</b><b style="color:#FFFFF1">n</b><b style="color:#F5FF55">g</b><b style="color:#FFFFEE">G</b><b style="color:#F5FF4F">o</b><b style="color:#FEFFE5">n</b><b style="color:#F3FF3C">d</b><b style="color:#F6FF69">r</b><b style="color:#FFFFF5">o</b><b style="color:#FCFFC6">n</b><b style="color:#F5FF52">g</b><b style="color:#F5FF51">G</b><b style="color:#FEFFD7">o</b><b style="color:#F9FF85">n</b><b style="color:#F1FF22">d</b><b style="color:#F0FF25">r</b><b style="color:#F9FF8E">o</b><b style="color:#F9FF7F">n</b><b style="color:#FBFF92">g</b><b style="color:#FFFFFF">G</b><b style="color:#FCFFBF">o</b><b style="color:#F6FF55">n</b><b style="color:#FAFF8D">d</b><b style="color:#FFFFF9">r</b><b style="color:#FFFFFF">o</b><b style="color:#F9FF93">n</b><b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondr</b>
<b style="color:#FFFFFF">ongGondrongGondrongGondrongGondrongGond</b><b style="color:#FBFF9E">r</b><b style="color:#F1FF31">o</b><b style="color:#FBFFB4">n</b><b style="color:#FFFFFF">g</b><b style="color:#FAFF93">G</b><b style="color:#FFFFFF">on</b><b style="color:#F7FF77">d</b><b style="color:#FFFFF7">r</b><b style="color:#FEFFEA">o</b><b style="color:#FFFFFF">n</b><b style="color:#FDFFC2">g</b><b style="color:#FEFFE8">G</b><b style="color:#FFFFFF">o</b><b style="color:#FFFFFE">n</b><b style="color:#FAFF98">d</b><b style="color:#FBFFA1">r</b><b style="color:#FDFFD4">o</b><b style="color:#FFFFFF">ngG</b><b style="color:#FCFFAD">o</b><b style="color:#FFFFF1">n</b><b style="color:#FFFFFF">d</b><b style="color:#FBFFAB">r</b><b style="color:#FFFFFA">o</b><b style="color:#FCFFB3">n</b><b style="color:#FFFFF9">g</b><b style="color:#FCFFB3">G</b><b style="color:#FEFFDE">o</b><b style="color:#FFFFFF">n</b><b style="color:#F9FF88">d</b><b style="color:#FFFFFE">r</b><b style="color:#FEFFE9">o</b><b style="color:#FBFFA4">n</b><b style="color:#FEFFE9">g</b><b style="color:#FAFF9B">G</b><b style="color:#FFFFF7">on</b><b style="color:#FFFFFF">d</b><b style="color:#F9FF92">r</b><b style="color:#FFFFFF">o</b><b style="color:#FEFFE0">n</b><b style="color:#FAFF8A">g</b><b style="color:#F7FF66">G</b><b style="color:#FFFFF1">o</b><b style="color:#FFFFFF">n</b><b style="color:#F9FF8A">d</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGo</b>
<b style="color:#FFFFFF">ndrongGondrongGondrongGondrongGondrongG</b><b style="color:#F7FF74">o</b><b style="color:#F9FF8D">n</b><b style="color:#FBFFAB">d</b><b style="color:#FFFFFF">r</b><b style="color:#FAFF8D">o</b><b style="color:#FFFFFE">n</b><b style="color:#FFFFFF">g</b><b style="color:#F9FF95">G</b><b style="color:#FFFFFF">ond</b><b style="color:#FDFFBA">r</b><b style="color:#FEFFD8">o</b><b style="color:#FFFFFF">n</b><b style="color:#FFFFFA">g</b><b style="color:#FEFFD2">G</b><b style="color:#FFFFF0">o</b><b style="color:#F9FF83">n</b><b style="color:#FFFFFF">dro</b><b style="color:#F9FF88">n</b><b style="color:#FDFFCF">g</b><b style="color:#FFFFFF">G</b><b style="color:#FBFFA5">o</b><b style="color:#FFFFF6">n</b><b style="color:#F9FF7A">d</b><b style="color:#FFFFF6">r</b><b style="color:#F9FF92">o</b><b style="color:#FBFF9E">n</b><b style="color:#FAFF92">g</b><b style="color:#F6FF66">G</b><b style="color:#FFFFF5">o</b><b style="color:#FEFFDE">n</b><b style="color:#FCFFAE">d</b><b style="color:#FEFFEB">r</b><b style="color:#FDFFC2">o</b><b style="color:#FFFFFF">ngG</b><b style="color:#F7FF82">o</b><b style="color:#FFFFFE">n</b><b style="color:#FBFF98">d</b><b style="color:#FEFFD4">r</b><b style="color:#FBFFA5">o</b><b style="color:#FEFFE2">n</b><b style="color:#FFFFFF">g</b><b style="color:#F9FF90">G</b><b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondron</b>
<b style="color:#FFFFFF">gGondrongGondrongGondrongGondrongGondr</b><b style="color:#FEFFEA">o</b><b style="color:#F5FF51">n</b><b style="color:#FEFFE5">g</b><b style="color:#F6FF58">G</b><b style="color:#F9FF82">o</b><b style="color:#EFFF21">n</b><b style="color:#F9FF87">d</b><b style="color:#FDFFD1">r</b><b style="color:#F1FF31">o</b><b style="color:#FDFFD4">n</b><b style="color:#FFFFFF">g</b><b style="color:#FBFFA7">G</b><b style="color:#F5FF51">o</b><b style="color:#F7FF64">n</b><b style="color:#FDFFD6">d</b><b style="color:#FFFFFC">r</b><b style="color:#F5FF52">o</b><b style="color:#F8FF6C">n</b><b style="color:#FDFFCA">g</b><b style="color:#FFFFFF">Go</b><b style="color:#FFFFF3">n</b><b style="color:#F3FF38">d</b><b style="color:#F9FF87">r</b><b style="color:#FFFFFF">o</b><b style="color:#FDFFBF">n</b><b style="color:#F2FF38">g</b><b style="color:#F0FF22">G</b><b style="color:#FAFF98">o</b><b style="color:#FEFFE5">n</b><b style="color:#EEFF11">d</b><b style="color:#F7FF77">r</b><b style="color:#FEFFE9">o</b><b style="color:#F6FF55">n</b><b style="color:#F4FF41">g</b><b style="color:#FEFFE7">G</b><b style="color:#F9FF85">o</b><b style="color:#F5FF4B">n</b><b style="color:#FFFFFD">d</b><b style="color:#FFFFF6">r</b><b style="color:#F8FF7A">o</b><b style="color:#F5FF49">n</b><b style="color:#F9FF80">g</b><b style="color:#FBFFA4">G</b><b style="color:#F9FF8E">o</b><b style="color:#F8FF7D">n</b><b style="color:#F9FF75">d</b><b style="color:#F6FF58">r</b><b style="color:#F1FF2E">o</b><b style="color:#F6FF60">n</b><b style="color:#FFFFF1">g</b><b style="color:#FFFFFF">GondrongGondrongGondrongGondrongGond</b>
<b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongGondr</b><b style="color:#FFFFFE">o</b><b style="color:#FFFFF9">n</b><b style="color:#FFFFFB">g</b><b style="color:#FFFFFC">G</b><b style="color:#FFFFFE">o</b><b style="color:#FFFFFD">n</b><b style="color:#FFFFFF">dr</b><b style="color:#FEFFF1">o</b><b style="color:#FFFFFA">n</b><b style="color:#FFFFFF">g</b><b style="color:#FFFFFE">G</b><b style="color:#FFFFFF">o</b><b style="color:#FFFFFE">n</b><b style="color:#FFFFFF">drongGond</b><b style="color:#FFFFFA">r</b><b style="color:#FFFFFE">o</b><b style="color:#FFFFFD">n</b><b style="color:#FFFFFF">g</b><b style="color:#FFFFF7">G</b><b style="color:#FFFFFE">o</b><b style="color:#FFFFFF">n</b><b style="color:#FFFFFB">d</b><b style="color:#FFFFF9">r</b><b style="color:#FFFFFF">o</b><b style="color:#FFFFFD">n</b><b style="color:#FFFFFE">g</b><b style="color:#FFFFFF">G</b><b style="color:#FFFFFE">o</b><b style="color:#FEFFF0">n</b><b style="color:#FFFFFE">dr</b><b style="color:#FFFFFF">o</b><b style="color:#FFFFFE">n</b><b style="color:#FFFFFF">gG</b><b style="color:#FFFFF6">o</b><b style="color:#FFFFFC">n</b><b style="color:#FFFFF9">d</b><b style="color:#FFFFFF">rongGondrongGondrongGondrongGondrongG</b>
<b style="color:#FFFFFF">ondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondro</b>
<b style="color:#FFFFFF">ngGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGondrongGon</b>
</pre>
 




echo color("green","▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n");
echo color("white","[•]  Time  : ".date("l, Y-m-d H:i:s")."   \n");
echo color("green","▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n");
echo color("white","[•]              Gondrong      \n");
echo color("green","▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n");
function change(){
        $nama = nama();
        $email = str_replace(" ", "", $nama) . mt_rand(100, 999);
        ulang:
        echo color("nevy","(•) Nomor : ");
        $no = trim(fgets(STDIN));
        $data = '{"email":"'.$email.'@gmail.com","name":"'.$nama.'","phone":"+'.$no.'","signed_up_country":"ID"}';
        $register = request("/v5/customers", null, $data);
        if(strpos($register, '"otp_token"')){
        $otptoken = getStr('"otp_token":"','"',$register);
        echo color("green","+] Kode verifikasi sudah di kirim")."\n";
        otp:
        echo color("nevy","?] Otp: ");
        $otp = trim(fgets(STDIN));
        $data1 = '{"client_name":"gojek:cons:android","data":{"otp":"' . $otp . '","otp_token":"' . $otptoken . '"},"client_secret":"83415d06-ec4e-11e6-a41b-6c40088ab51e"}';
        $verif = request("/v5/customers/phone/verify", null, $data1);
        if(strpos($verif, '"access_token"')){
        echo color("green","+] Bersil mendaftar");
        $token = getStr('"access_token":"','"',$verif);
        $uuid = getStr('"resource_owner_id":',',',$verif);
        echo "\n".color("yellow","+] Your access token : ".$token."\n\n");
        save("token.txt",$token);
        echo "\n".color("nevy","?] Mau Redeem Voucher?: y/n ");
        $pilihan = trim(fgets(STDIN));
        if($pilihan == "y" || $pilihan == "Y"){
        echo color("red","===========(REDEEM VOUCHER)===========");
        echo "\n".color("yellow","!] Claim A");
        echo "\n".color("yellow","!] Please wait");
        for($a=1;$a<=3;$a++){
        echo color("yellow",".");
        sleep(3);
        }
        $code1 = request('/go-promotions/v1/promotions/enrollments', $token, '{"promo_code":"GOSENDHEMAT"}');
        $message = fetch_value($code1,'"message":"','"');
        if(strpos($code1, 'Promo kamu sudah bisa dipakai')){
        echo "\n".color("green","+] Message: ".$message);
        goto gocar;
        }else{
        echo "\n".color("red","-] Message: ".$message);
        gocar:
        echo "\n".color("yellow","!] Claim B");
        echo "\n".color("yellow","!] Please wait");
        for($a=1;$a<=3;$a++){
        echo color("yellow",".");
        sleep(20);
        }
        $code1 = request('/go-promotions/v1/promotions/enrollments', $token, '{"promo_code":"GOJEKINAJA"}');
        $message = fetch_value($code1,'"message":"','"');
        if(strpos($code1, 'Promo kamu sudah bisa dipakai')){
        echo "\n".color("green","+] Message: ".$message);
        goto gofood;
        }else{
        echo "\n".color("red","-] Message: ".$message);
        reff:
        $data = '{"referral_code":"GOJEKINAJA"}';    
        $claim = request("/customer_referrals/v1/campaign/enrolment", $token, $data);
        $message = fetch_value($claim,'"message":"','"');
        if(strpos($claim, 'Promo kamu sudah bisa dipakai')){
        echo "\n".color("green","+] Message: ".$message);
        goto gofood;
        }else{
        echo "\n".color("red","-] Message: ".$message);
        }
        gofood:
        echo "\n".color("yellow","!] Claim C");
        echo "\n".color("yellow","!] Please wait");
        for($a=1;$a<=3;$a++){
        echo color("yellow",".");
        sleep(3);
        }
        $code1 = request('/go-promotions/v1/promotions/enrollments', $token, '{"promo_code":"GOJEKHEMAT"}');
        $message = fetch_value($code1,'"message":"','"');
        if(strpos($code1, 'Promo kamu sudah bisa dipakai')){
        echo "\n".color("green","+] Message: ".$message);
        sleep(1);
        sleep(3);
        $cekvoucher = request('/gopoints/v3/wallet/vouchers?limit=10&page=1', $token);
        $total = fetch_value($cekvoucher,'"total_vouchers":',',');
        $voucher3 = getStr1('"title":"','",',$cekvoucher,"3");
        $voucher1 = getStr1('"title":"','",',$cekvoucher,"1");
        $voucher2 = getStr1('"title":"','",',$cekvoucher,"2");
        $voucher4 = getStr1('"title":"','",',$cekvoucher,"4");
        $voucher5 = getStr1('"title":"','",',$cekvoucher,"5");
        $voucher6 = getStr1('"title":"','",',$cekvoucher,"6");
        echo "\n".color("yellow","!] Total voucher ".$total." : ");
        echo color("green","1. ".$voucher1);
        echo "\n".color("green","                     2. ".$voucher2);
        echo "\n".color("green","                     3. ".$voucher3);
        echo "\n".color("green","                     4. ".$voucher4);
        echo "\n".color("green","                     5. ".$voucher5);
        echo "\n".color("green","                     6. ".$voucher6);
        $expired1 = getStr1('"expiry_date":"','"',$cekvoucher,'1');
        $expired2 = getStr1('"expiry_date":"','"',$cekvoucher,'2');
        $expired3 = getStr1('"expiry_date":"','"',$cekvoucher,'3');
        $expired4 = getStr1('"expiry_date":"','"',$cekvoucher,'4');
        $expired5 = getStr1('"expiry_date":"','"',$cekvoucher,'5');
        $expired6 = getStr1('"expiry_date":"','"',$cekvoucher,'6');
         setpin:
         echo "\n".color("nevy","?] Mau set pin?: y/n ");
         $pilih1 = trim(fgets(STDIN));
         if($pilih1 == "y" || $pilih1 == "Y"){
         //if($pilih1 == "y" && strpos($no, "628")){
         echo color("red","========( PIN ANDA = 112233 )========")."\n";
         $data2 = '{"pin":"112233"}';
         $getotpsetpin = request("/wallet/pin", $token, $data2, null, null, $uuid);
         echo "Otp set pin: ";
         $otpsetpin = trim(fgets(STDIN));
         $verifotpsetpin = request("/wallet/pin", $token, $data2, null, $otpsetpin, $uuid);
         echo $verifotpsetpin;
         }else if($pilih1 == "n" || $pilih1 == "N"){
         die();
         }else{
         echo color("red","-] GAGAL!!!\n");
         }
         }
         }
         }
         }else{
         goto setpin;
         }
         }else{
         echo color("red","-] Otp yang anda input salah");
         echo"\n==================================\n\n";
         echo color("yellow","!] Silahkan input kembali\n");
         goto otp;
         }
         }else{
         echo color("red","NOMOR SUDAH TERDAFTAR/SALAH !!!");
         echo "\nMau ulang? (y/n): ";
         $pilih = trim(fgets(STDIN));
         if($pilih == "y" || $pilih == "Y"){
         echo "\n==============Register==============\n";
         goto ulang;
         }else{
         echo "\n==============Register==============\n";
         goto ulang;
  }
 }
}
echo change()."\n"; ?>
